### ISSUE TITLE
Exception: unexpected fixed contents: got b'', was waiting for b'GIF'

### ISSUE THREAD

**Issue by Cesar-mlw** [bodqhrohro/giftolottie#10]
There seems to be a problem with gif2numpy. I'm running on Windows10 by the way. 

```
Traceback (most recent call last):
  File "read.py", line 22, in <module>
    frames, exts, image_specs = vendor.gif2numpy.convert(tmpfile.name, BGR2RGB=False)
  File "C:\Users\Cesar MLW\Desktop\Projects\gif_converter\giftolottie\vendor\gif2numpy.py", line 550, in convert
    data = Gif(KaitaiStream(BytesIO(raw)))
  File "C:\Users\Cesar MLW\Desktop\Projects\gif_converter\giftolottie\vendor\gif2numpy.py", line 82, in __init__
    self._read()
  File "C:\Users\Cesar MLW\Desktop\Projects\gif_converter\giftolottie\vendor\gif2numpy.py", line 85, in _read
    self.hdr = self._root.Header(self._io, self, self._root)
  File "C:\Users\Cesar MLW\Desktop\Projects\gif_converter\giftolottie\vendor\gif2numpy.py", line 263, in __init__
    self._read()
  File "C:\Users\Cesar MLW\Desktop\Projects\gif_converter\giftolottie\vendor\gif2numpy.py", line 266, in _read
    self.magic = self._io.ensure_fixed_contents(b"\x47\x49\x46")
  File "C:\Users\Cesar MLW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\kaitaistruct.py", line 279, in ensure_fixed_contents
    (actual, expected)
Exception: unexpected fixed contents: got b'', was waiting for b'GIF'
```

**Comment by lalettan-fan** [comment]
i am running on ubuntu and the same error occured

**Comment by bodqhrohro** [comment]
Are you sure you provide a valid GIF file as an input? Seems like the file contains something other actually.

**Comment by kopyl** [comment]
> Are you sure you provide a valid GIF file as an input? Seems like the file contains something other actually.

I am

![patrick-bateman-sigma](https://github.com/user-attachments/assets/3a37b260-693b-434f-8f0b-8edf6ce82718)

**Comment by bodqhrohro** [comment]
@kopyl it's another error, see #5

Anyway, this GIF is too large and dithered for a vector sticker.
