### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/smile0.svg'

### ISSUE THREAD

**Issue by Pineapple1001** [bodqhrohro/giftolottie#11]
Traceback (most recent call last):
  File "C:/Users/user/Desktop/giftolottie-5131a368607ebb177f2d61d6564c61264dbfbcd0/read.py", line 71, in <module>
    svg_save(all_rects, "/tmp/smile%s.svg" % i)
  File "C:\Users\user\Desktop\giftolottie-5131a368607ebb177f2d61d6564c61264dbfbcd0\export\svg.py", line 18, in save
    svg.save()
  File "C:\Users\user\AppData\Local\Programs\Python\Python38-32\lib\site-packages\svgwrite\drawing.py", line 121, in save
    fileobj = io.open(self.filename, mode='w', encoding='utf-8')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/smile0.svg'

**Comment by bodqhrohro** [comment]
You seem to use an outdated revision, I commented this line out in 24ee427a0ccebc41073e6f33a2697366380e7424.
