### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'gifsicle'

### ISSUE THREAD

**Issue by F36** [bodqhrohro/giftolottie#12]
Getting this error

python3 read.py input.gif output.tgs
Traceback (most recent call last):
  File "read.py", line 19, in <module>
    run(["gifsicle", "-U", sys.argv[1]], stdout=tmpfile)
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.8/subprocess.py", line 1700, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gifsicle'

**Comment by nikitalita** [comment]
install gifsicle

**Comment by F36** [comment]
> install gifsicle

is this correct pip install pygifsicle

**Comment by nikitalita** [comment]
nope

**Comment by F36** [comment]
> nope

then how plz tell

**Comment by kidneyweakx** [comment]
> then how plz tell

@F36  Just install gifsicle from [official website](https://www.lcdf.org/gifsicle/)

And put the gifsicle.exe in the directory

**Comment by bchooxg** [comment]
brew install gifsicle if you have home brew on mac

**Comment by bodqhrohro** [comment]
@kidneyweakx @bchooxg it is clear from the backtrace this is neither Windows nor macOS, but Android.

If gifsicle is absent from Termux repos, I may suggest installing a full-fledged Debian or other distribution via AnLinux in Termux, if you have enough space.
