### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by tomek3001** [bodqhrohro/giftolottie#13]
> Traceback (most recent call last):
>  File "read.py", line 19, in <module>
>    run(["gifsicle", "-U", sys.argv[1]], stdout=tmpfile)
>  File "D:\ProgramFiles\miniconda3\lib\subprocess.py", line 488, in run
>    with Popen(*popenargs, **kwargs) as process:
>  File "D:\ProgramFiles\miniconda3\lib\subprocess.py", line 800, in __init__
>    restore_signals, start_new_session)
>  File "D:\ProgramFiles\miniconda3\lib\subprocess.py", line 1207, in _execute_child
>    startupinfo)
>FileNotFoundError: [WinError 2] Nie można odnaleźć określonego pliku

while executing
> python read.py wale.gif wale.tgs

wale.gif is in the read.py's directory

**Comment by linssab** [comment]
I'm having the same issue when trying to load Gif's from either root or any folder within 
`python read.py ./inputs/1.gif 1.tgs`

Maybe this is a Miniconda3 related error?

**Comment by Oleg-A-LLIto** [comment]
Chances are you are missing gifsicle, not your file. Make sure gifsicle is in PATH.
