### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by dmirajkar** [bodqhrohro/giftolottie#16]
IndexError: list index out of range

**Comment by EverythingSuckz** [comment]
Yeah same issue here

```
╭─wrench@Alligator in repo: giftolottie on  master [?] via  v3.9.6 took 79ms
╰─λ python read.py  test.gif out.tgs

Traceback (most recent call last):
File "/home/wrench/Documents/Github/giftolottie/read.py", line 22, in <module>
frames, exts, image_specs = vendor.gif2numpy.convert(tmpfile.name, BGR2RGB=False)
File "/home/wrench/Documents/Github/giftolottie/vendor/gif2numpy.py", line 660, in convert
transp_idx = color_table[exts[-1]['transparent_idx']] # RGB -> RGB
IndexError: list index out of range
```

**Comment by john-terraform** [comment]
Same here

```
Traceback (most recent call last):
  File "/home/keereal/github-personal/giftolottie/read.py", line 22, in <module>
    frames, exts, image_specs = vendor.gif2numpy.convert(tmpfile.name, BGR2RGB=False)
  File "/home/keereal/github-personal/giftolottie/vendor/gif2numpy.py", line 660, in convert
    transp_idx = color_table[exts[-1]['transparent_idx']] # RGB -> RGB
IndexError: list index out of range
```

**Comment by RiedleroD** [comment]
see #5
