### ISSUE TITLE
TypeError: 'ColorTable' object is not subscriptable

### ISSUE THREAD

**Issue by Drjacky** [bodqhrohro/giftolottie#18]
First, I had this error:
```pyhton
Traceback (most recent call last):
  File "giftotgs/giftolottie/read.py", line 19, in <module>
    run(["gifsicle", "-U", sys.argv[1]], stdout=tmpfile)
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gifsicle'
```

So, I run `pip3 install pygifsicle`; Which I'm not if that was correct way to have `gifsicle`!

Then, I got this:
```python
➜  giftolottie git:(master) python3 read.py sample.gif output.tgs
gifsicle:sample.gif: warning: GIF too complex to unoptimize
  (The reason was local color tables or complex transparency.
  Try running the GIF through ‘gifsicle --colors=255’ first.)
gifsicle: warning: too many colors, using local colormaps
  (You may want to try ‘--colors 256’.)
Traceback (most recent call last):
  File "giftotgs/giftolottie/read.py", line 22, in <module>
    frames, exts, image_specs = vendor.gif2numpy.convert(tmpfile.name, BGR2RGB=False)
  File "giftotgs/giftolottie/vendor/gif2numpy.py", line 629, in convert
    np_image = np.array([local_color_table[byt] if byt != exts[-1]['transparent_idx'] else (254, 0, 254) for byt in uncompressed])
  File "giftotgs/giftolottie/vendor/gif2numpy.py", line 629, in <listcomp>
    np_image = np.array([local_color_table[byt] if byt != exts[-1]['transparent_idx'] else (254, 0, 254) for byt in uncompressed])
TypeError: 'ColorTable' object is not subscriptable
```

**Comment by Drjacky** [comment]
I even installed `pip3 install gif2numpy` but, didn't help - Still the same error.

**Comment by Drjacky** [comment]
I installed the requirements and now I get this:
```bash
Traceback (most recent call last):
  File "/Users/giftolottie/read.py", line 22, in <module>
    frames, exts, image_specs = vendor.gif2numpy.convert(tmpfile.name, BGR2RGB=False)
  File "/Users/giftolottie/vendor/gif2numpy.py", line 660, in convert
    transp_idx = color_table[exts[-1]['transparent_idx']] # RGB -> RGB
IndexError: list index out of range
```

**Comment by bodqhrohro** [comment]
See #5.

Sorry for not replying to the previous comments: have no idea how did I miss it even after discovering the notifications problem.

**Comment by Drjacky** [comment]
@bodqhrohro https://github.com/bodqhrohro/giftolottie/issues/5#issuecomment-1217983430
