### ISSUE TITLE
File "read.py", line 15, in <module>

### ISSUE THREAD

**Issue by Kargevon** [bodqhrohro/giftolottie#9]
Traceback (most recent call last):
  File "read.py", line 15, in <module>
    from export.svg import save as svg_save
  File "/home/pavel08052002/giftolottie/export/svg.py", line 1, in <module>
    import svgwrite
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/__init__.py", line 53, in <module>
    from svgwrite.drawing import Drawing
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/drawing.py", line 29, in <module>
    from svgwrite.container import SVG, Defs
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/container.py", line 28, in <module>
    from svgwrite.base import BaseElement
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/base.py", line 16, in <module>
    from svgwrite.params import Parameter
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/params.py", line 9, in <module>
    from svgwrite.validator2 import get_validator
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/validator2.py", line 9, in <module>
    from svgwrite.data import full11
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/data/full11.py", line 11, in <module>
    from svgwrite.data.typechecker import Full11TypeChecker as TypeChecker
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/data/typechecker.py", line 13, in <module>
    from svgwrite.data.svgparser import is_valid_transferlist, is_valid_pathdata, is_valid_animation_timing
  File "/home/pavel08052002/.local/lib/python3.5/site-packages/svgwrite/data/svgparser.py", line 24
    nonnegative_number = fr"(\d+\.?\d*|\.\d+){exponent}?"
                                                        ^
SyntaxError: invalid syntax

**Comment by Kargevon** [comment]
В чем проблема, как починить?

**Comment by bodqhrohro** [comment]
svgwrite использует f-строки, а они поддерживаются только с Python 3.6.
